version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - database-data:/var/lib/postgresql/data/
      - ./database/initial_script.sql:/docker-entrypoint-initdb.d/initial_script.sql
volumes:
  database-data:
